version: '3'

networks:
  elk:

volumes:
  elasticsearch:
    driver: local

services:

  elasticsearch:
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    networks:
      elk: null
    ports:
    - 9200:9200
    - 9300:9300
    restart: unless-stopped
    volumes:
    - /dockerdata/elasticsearch/volumemount:/usr/share/elasticsearch/data:rw

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.2.0
    container_name: logstash
    depends_on:
    - elasticsearch
    networks:
      elk: null
    ports:
    - "5044:5044"
    - "5000:5000"
    - "25826:25826/udp"

    restart: unless-stopped
    volumes:
    - /dockerdata/logstash/pipeline/conf.d:/usr/share/logstash/pipeline:rw

  kibana:
    depends_on:
    - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    container_name: kibana
    image: docker.elastic.co/kibana/kibana-oss:7.2.0
    networks:
      elk: null
    ports:
    - 5601:5601
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      elk: null
    ports:
      - "80:80"
    volumes:
      - /dockerdata/nginx/nginx.conf:/etc/nginx/nginx.conf:rw

